apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          # Mount the PVC at /data/db
          volumeMounts:
            - name: data
              mountPath: /data/db
          # Load root credentials from the secret
          envFrom:
            - secretRef:
                name: mongo-env
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pvc