apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: backend
          image: ghcr.io/edinify/robi-ser:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: backend-env
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          resources:
            requests:
              memory: "200Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "800m"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: backend-logs-pvc