apiVersion: v1
kind: Service 
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  labels:
    app: {{ .Release.Name }}-nginx-ingress
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-nginx-ingress